AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: apps/api/src/features/health/healthHandler.handler
      Runtime: nodejs22.x
      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - apps/api/src/features/health/healthHandler.ts

  CreateFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: apps/api/src/features/files/handlers/createFileHandler.createFileHandler
      Runtime: nodejs22.x
      Events:
        CreateFilesApi:
          Type: Api
          Properties:
            Path: /files
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - apps/api/src/features/files/handlers/createFileHandler.ts

  GetFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: apps/api/src/features/files/handlers/getFilesHandler.getFilesHandler
      Runtime: nodejs22.x
      Events:
        GetFilesApi:
          Type: Api
          Properties:
            Path: /files
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - apps/api/src/features/files/handlers/getFilesHandler.ts

  GetFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: apps/api/src/features/files/handlers/getFileHandler.getFileHandler
      Runtime: nodejs22.x
      Events:
        GetFilesApi:
          Type: Api
          Properties:
            Path: /files/{id}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - apps/api/src/features/files/handlers/getFileHandler.ts

  DeleteFileByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: apps/api/src/features/files/handlers/deleteFileByIdHandler.deleteFileByIdHandler
      Runtime: nodejs22.x
      Events:
        DeleteFileByIdApi:
          Type: Api
          Properties:
            Path: /files/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - apps/api/src/features/files/handlers/deleteFileByIdHandler.ts
